### ISSUE TITLE
Server Guide docs are out of date (?)

### ISSUE THREAD

**Issue by weisjohn** [rackt/react-router#1466]
Based on the line `import Location from 'react-router/lib/Location';` from https://github.com/rackt/react-router/blob/master/doc/00%20Guides/Server%20Rendering.md ,  I'm getting Error: Cannot find module 'react-router/modules/Location'.

I'm unsure as how to proceed, as the new API doesn't have a simple Location object. 

I did find a `StaticLocation` class:

```
var router = require('react-router');
loc = new router.StaticLocation('/');
```

Can anyone confirm this is the correct understanding?

**Comment by tmbtech** [comment]
What version of react-router are you using?

**Comment by israelidanny** [comment]
Getting the same problem after upgrading from 1.0.0-beta3 to 0.13.3

**Comment by tmbtech** [comment]
1.0-beta-3 is the newest.

**Comment by gaearon** [comment]
Please don't read docs in the repo.
They are work in progress and don't reflect the stable version: https://github.com/rackt/react-router/commit/44a1692d97b95cd4f1cf995d97a55eb2da7dcd86.

Instead, read them on the website: http://rackt.github.io/react-router.
It defaults to the latest released version (0.13.3).
