### ISSUE TITLE
Cannot find module 'deep-equal'

### ISSUE THREAD

**Issue by abhijeetNmishra** [rackt/react-router#2788]
getting this error after upgrading to v2.0

Client side code : 

```
....
import { browserHistory } from 'react-router';
....

  <Root history={ browserHistory } store={ store } />
```

server side code 

```
....
import { Router, RouterContext, match } from 'react-router';
....

match({routes:getRoutes,location: req.originalUrl},(error,redirectLocation,renderProps) => {
       const component = (
        <Provider store={store} key="provider">
          <RouterContext {...renderProps} />
        </Provider>
      )
.....
```

I believe issue is on server side implementation.

**Comment by patrickheeney** [comment]
Same for me: https://github.com/rackt/react-router/issues/2785#issuecomment-168081103

**Comment by taion** [comment]
Might be a consequence of the packaging thing, or else just a busted install on your end. This package doesn't use `deep-equal`. Might be fixed by #2785.
