### ISSUE TITLE
Not work with react 0.13.0-beta.1 anymore

### ISSUE THREAD

**Issue by rottmann** [rackt/react-router#818]
v 0.11 does.

`Uncaught TypeError: undefined is not a function`
`createRouter.js?08c1:317 Uncaught TypeError: undefined is not a function`
```
      handleLocationChange: function (change) {
        this.dispatch(change.path, change.type);
      },
```

**Comment by Azerothian** [comment]
React 0.13 has Autobinding removed, react-router will need to reworked to take this in account.
see. http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

**Comment by gaearon** [comment]
I don't think React 0.13 removes autobinding for `createClass` classes (which router is). It's just not enabled on ES6-y classes.

**Comment by Azerothian** [comment]
Sorry your right, i read that wrong, thanks.

https://github.com/rackt/react-router/tree/master/examples/simple-master-detail

I went and imported an example into jsfiddle, using router 0.11.6 and react 13.0.beta.1 has lots of warnings firing but it is working fine.

http://jsfiddle.net/y2nmyryf/7/

@rottmann, can you please provide example code of this error?

**Comment by taurose** [comment]
I also get this by just running the examples.

Not sure if this react change is intentional or not. As far as I can tell the problematic commit is [this](https://github.com/facebook/react/pull/2375/files) (search for `proxyStaticMethods` which is removed without replacement). So this auto binding functionality for statics might have been part of the factory provided by createClass, which they wanted to get rid of.

**Comment by zpao** [comment]
Just talked with @sebmarkbage - it is intentional.

**Comment by mjackson** [comment]
ok, looks like we need to stop relying on auto-binding. Let's follow up in #638

**Comment by vu3mmg** [comment]
Do you have  an example of react router  , which i could copy to an html  and see how it works .
I was able to run the examples from git hub. But when i try to create my own in a separate file it is not working . I am not getting any errors . Some basic problem..
