### ISSUE TITLE
react-router eats stack traces in willTransitionTo (and subsequently component*Mount)

### ISSUE THREAD

**Issue by DelvarWorld** [rackt/react-router#946]
A frustrating behavior of the router:

https://github.com/rackt/react-router/blob/master/modules/Transition.js#L60

If you have any errors in your component mounting / instantiating, they are eaten by the router. All you'll get in the console is something like "Undefined is not a function" but no stack trace. I believe this is because the mount* functions get called synchronously, so when that code calls `callback` it triggers the React land component stuff, and any errors are caught by the `try catch`. The error eventually gets thrown here:

https://github.com/rackt/react-router/blob/e0a15ebc81d76119935fef27e0ab7d7b024b98fd/modules/createRouter.js#L303

This makes it very hard to debug errors in component instantiation.

This can be reproduced very simply by making a component with a `willTransitionTo` that has a runtime error either in the `willTransitionTo` or in the `render`.

**Comment by DelvarWorld** [comment]
Update to this issue, it's something that was introduced in *0.12.x* it appears.

The initial bug report above is slightly incorrect. I wasn't seeing a stack trace because I was calling `Routes.run` inside of a promise. However, you can still see the stack trace originating from the wrong place, making debugging difficult, in this JSFiddle: http://jsfiddle.net/qn68sdg6/8/

**Comment by chollier** [comment]
I've seen the same issue since I update to 0.12 as well

**Comment by DelvarWorld** [comment]
Two undesirable workarounds:

1. For debugging, you can manually edit `node_modules/react-router/modules/Transition.js`` and commet out the try / catch lines.

2. You can downgrade to 0.11.x, [as long as you aren't using `transition.wait`](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md) : `"react-router": "0.11.6",` which does not have this behavior

**Comment by johanneslumpe** [comment]
@DelvarWorld here is a more desirable fix: http://jsfiddle.net/qn68sdg6/10/

Pass a custom `onError` method when you are creating the router, and then just re-throw the error. You should see a full stack trace in your console.

**Comment by jeffutter** [comment]
I think this may be the same issue I was experiencing here: #935

**Comment by johanneslumpe** [comment]
@jeffutter yeah seems like it. Sorry, didn't see your issue. But the same solution should apply :)

**Comment by jquense** [comment]
@johanneslumpe does that work? the `onError` in your workaround is the default value of `onError` https://github.com/rackt/react-router/blob/e0a15ebc81d76119935fef27e0ab7d7b024b98fd/modules/createRouter.js#L301

**Comment by johanneslumpe** [comment]
Yeah is the same. But it does give you a full stack trace - I'm not sure about the logic behind this though and why it behaves differently. ;)

**Comment by johanneslumpe** [comment]
Actually I assume that the difference is that I am defining the callback outside of the component, so the scope is different. But that's just a wild guess.

**Comment by gaearon** [comment]
I'm a but confused, won't “Pause on All Exceptions” work in this case?

**Comment by taurose** [comment]
I guess so, but that seems like a bad excuse :smile:

The way I see it, there are two problems:

1. When using transition hooks, the whole routing process afterwards (including run callback and synchronous render calls) will be wrapped within the try catch block of Transition.js. See #981

2. Some browsers seem to have trouble reporting rethrown errors (e.g. only pointing to the line the error was rethrown, instead of showing the original stack trace). Possibly related to https://code.google.com/p/chromium/issues/detail?id=432516

We should be able to fix 1), but I'm not sure what to do about 2).

**Comment by ryanflorence** [comment]
;_;

we need to fix this, nothing aggravates me more than stuff like this. It's got to give you a stack trace with the real line of code that has the problem.

**Comment by jeffutter** [comment]
Any movement on this?

**Comment by jeffutter** [comment]
I ask because it seems like ReactRouter is breaking stack traces on react warnings too? I'm getting warnings like:
```Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child. warning.js:48```
With no trace. At least I assume it is coming from the same problem as this issue.

**Comment by tnrich** [comment]
+1 for a fix. I'm also running into this issue right now and it is quite frustrating.

**Comment by ryanflorence** [comment]
in 1.0 there is only one `try/catch` in HashHistory when trying to parse some JSON in session storage.

So if your errors are swallowed it ain't us! :dash:

**Comment by eranimo** [comment]
I think it's react router's fault. When you remove react router, the problem goes away...
