### ISSUE TITLE
Got this error after upgrading to 0.12

### ISSUE THREAD

**Issue by marksteve** [rackt/react-router#815]
```
Warning: Required context `getRouteComponents` was not specified in `RouteHandler`. Check the render method of `Component`.
Uncaught TypeError: undefined is not a function
```

**Comment by gaearon** [comment]
Do you have other details to reproduce this? Do you do anything unusual with React elements? (e.g. creating them outside `render` of parent component, passing them up or something)

This should completely go away with React 0.14 but while it's not solved, more information (or a repro project) would help.
